### ISSUE TITLE
Cannot update bluetooth after kernel update

### ISSUE THREAD

**Issue by codyswanner** [jeremyb31/bluetooth-6.8#1]
Hi @jeremyb31!  You helped me on [this AskUbuntu question](https://askubuntu.com/questions/1517805/bluetooth-not-discovering-devices-driver-current-kubuntu-24-04) (thank you by the way!), but since my last kernel update I have not been able to use bluetooth, it's the same situation as before where it appears active and shows scanning (or I explicitly enable scanning in the terminal) but it never finds any devices.

I followed the instructions you gave in your answer to me originally and got an error, here's the logs for that:
```
DKMS make.log for btusb-4.1 for kernel 6.8.0-45-generic (x86_64)
Sat Oct 12 08:52:56 AM CDT 2024
make -C /lib/modules/6.8.0-45-generic/build M=/var/lib/dkms/btusb/4.1/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.8.0-45-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0
  You are using:           gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0
  CC [M]  /var/lib/dkms/btusb/4.1/build/btusb.o
/var/lib/dkms/btusb/4.1/build/btusb.c: In function ‘btusb_probe’:
/var/lib/dkms/btusb/4.1/build/btusb.c:4317:21: error: ‘struct hci_dev’ has no member named ‘dev_type’
 4317 |                 hdev->dev_type = HCI_AMP;
      |                     ^~
/var/lib/dkms/btusb/4.1/build/btusb.c:4317:34: error: ‘HCI_AMP’ undeclared (first use in this function); did you mean ‘HCI_UP’?
 4317 |                 hdev->dev_type = HCI_AMP;
      |                                  ^~~~~~~
      |                                  HCI_UP
/var/lib/dkms/btusb/4.1/build/btusb.c:4317:34: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/btusb/4.1/build/btusb.c:4319:21: error: ‘struct hci_dev’ has no member named ‘dev_type’
 4319 |                 hdev->dev_type = HCI_PRIMARY;
      |                     ^~
/var/lib/dkms/btusb/4.1/build/btusb.c:4319:34: error: ‘HCI_PRIMARY’ undeclared (first use in this function); did you mean ‘HCI_PRIVACY’?
 4319 |                 hdev->dev_type = HCI_PRIMARY;
      |                                  ^~~~~~~~~~~
      |                                  HCI_PRIVACY
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/btusb/4.1/build/btusb.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.8.0-45-generic/Makefile:1925: /var/lib/dkms/btusb/4.1/build] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-45-generic'
make: *** [Makefile:7: all] Error 2
```

I saw some instructions you gave to [someone else](https://askubuntu.com/questions/1277459/bluetooth-rtl8723be-does-not-find-devices-on-lenovo-ideapad-100-14iby) on AskUbuntu for updating the bluetooth drivers after a kernel update, but following those instructions generates a similar error.

DKMS also mentioned `ERROR (dkms apport): binary package for btusb: 4.1 not found`, am I maybe missing some files?  At the time of your response to my original question I cloned this repo exactly and it worked at the time, but if I need to delete it all and start over with a fresh clone I can try that.

If I've got your attention anyways, just wanted to say thank you so much for helping me and so many people out with this, you are a rockstar!  If there's anything I can do to help you out with this or another project, let me know!

**Comment by jeremyb31** [comment]
Might have to remove the dkms, the cd into bluetooth-6.8 and do a git pull to get some updates

**Comment by codyswanner** [comment]
A little bit of learning how to dkms and that seems to have worked!  Thanks for the pointer!

**Comment by jeremyb31** [comment]
Good as I typed that last reply from my phone and didn't want to screw up the commands doing it from the phone
